apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha1
    kind: KubeSchedulerConfiguration
    schedulerName: scheduler-framework-redis
    leaderElection:
      leaderElect: true
      lockObjectName: scheduler-framework-redis
      lockObjectNamespace: kube-system
    plugins:
      filter:
        enabled:
        - name: "redis-scheduler"
      preBind:
        enabled:
        - name: "redis-scheduler"
    pluginConfig:
    - name: "redis-scheduler"
      args: {"node_num": 3}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-framework-redis
  namespace: kube-system
  labels:
    component: scheduler-framework-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler-framework-redis
  template:
    metadata:
      labels:
        component: scheduler-framework-redis
    spec:
      serviceAccount: redis-sa
      priorityClassName: system-cluster-critical
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
      containers:
      - name: scheduler-ctrl
        image: 192.168.15.128:5000/scheduler-framework-redis:latest
        imagePullPolicy: IfNotPresent
        args:
        - scheduler-framework-redis
        - --config=/scheduler/scheduler-config.yaml
        - --v=3
        resources:
          requests:
            cpu: "50m"
        volumeMounts:
        - name: scheduler-config
          mountPath: /scheduler
